# Generated by Django 5.2.4 on 2025-08-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('AircraftFlightHours', models.IntegerField()),
                ('AircraftCycles', models.IntegerField()),
                ('Landings', models.IntegerField()),
                ('airplane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bord.airplane')),
            ],
        ),
    ]
