# Generated by Django 5.2.4 on 2025-08-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0002_inputbord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flthrs',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bord.airplane'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bord.airplane'),
        ),
        migrations.AlterField(
            model_name='servicelifelimited',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bord.airplane'),
        ),
    ]
