# Generated by Django 5.2.4 on 2025-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0004_airplane_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flthrs',
            name='impact',
            field=models.CharField(choices=[('AircraftFlightHours', 'AircraftFlightHours'), ('AircraftCycles', 'AircraftCycles'), ('Landings', 'Landings')], default='AircraftFlightHours', max_length=100),
        ),
        migrations.AddField(
            model_name='mp',
            name='impact',
            field=models.CharField(choices=[('AircraftFlightHours', 'AircraftFlightHours'), ('AircraftCycles', 'AircraftCycles'), ('Landings', 'Landings')], default='AircraftFlightHours', max_length=100),
        ),
        migrations.AddField(
            model_name='servicelifelimited',
            name='impact',
            field=models.CharField(choices=[('AircraftFlightHours', 'AircraftFlightHours'), ('AircraftCycles', 'AircraftCycles'), ('Landings', 'Landings')], default='AircraftFlightHours', max_length=100),
        ),
    ]
