# Generated by Django 5.2.4 on 2025-09-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0005_flthrs_impact_mp_impact_servicelifelimited_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputbord',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bord.airplane'),
        ),
    ]
